# These are supported funding model platforms

buy_me_a_coffee: roniemartinez
github: [roniemartinez] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
open_collective: roniemartinez # Replace with a single Open Collective username
